### ISSUE TITLE
Using bayesloop with python3.11 does not work

### ISSUE THREAD

**Issue by rgerum** [christophmark/bayesloop#44]
I installed a new conda environment:

conda create -n env311 python=3.11 -y
conda activate env311
pip install bayesloop

then runing:

python -c "import bayesloop as bl"

produces this error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../anaconda3/envs/env311/lib/python3.11/site-packages/bayesloop/__init__.py", line 4, in <module>
    from .core import Study, HyperStudy, ChangepointStudy, OnlineStudy
  File "/home/.../anaconda3/envs/env311/lib/python3.11/site-packages/bayesloop/core.py", line 25, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/home/.../anaconda3/envs/env311/lib/python3.11/inspect.py)

Running the same with python 3.10 works. So its not an error with the installation.

**Comment by rgerum** [comment]
ah ok, this was directly your last commit to fix this. c1a6c96
Should have tried the repo first. 
Also more verbose commit messages might help ;-)
